environment:
  global:
    PGUSER: postgres
    PGPASSWORD: Password12!
    BOOST_ROOT: c:\libs\boost
    PREFIX: c:\libs
    PSQL_ROOT: C:\Program Files\PostgreSQL\9.4
    CMAKE_PREFIX_PATH: c:\libs;C:\Program Files\PostgreSQL\9.4
    PYTHONPATH: c:\libs
  matrix:
  - configuration: Release

# Operating system (build VM template)

os: Visual Studio 2015

services:
#  - postgresql # enable when Postgis will be available

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\osm2pgsql

clone_depth: 1

platform: x64

install:
  # by default, all script lines are interpreted as batch
  - cd c:\
  - mkdir libs
  - curl -O http://lonvia.de/osm2pgsql_win_deps.7z
  - 7z x osm2pgsql_win_deps.7z | find ":"

build_script:
  - mkdir c:\osm2pgsql\build
  - cd c:\osm2pgsql\build
  - echo Running cmake...
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cmake .. -LA -G "NMake Makefiles" -DBOOST_ROOT=%BOOST_ROOT% -DCMAKE_BUILD_TYPE=%Configuration% -DCMAKE_INSTALL_PREFIX=%PREFIX% -DBoost_USE_STATIC_LIBS=ON -DBUILD_TESTS=ON -DBZIP2_LIBRARY_RELEASE=C:/libs/lib/libbz2.lib -DZLIB_LIBRARY=C:\libs\lib\zlibwapi.lib
  - nmake
  - mkdir osm2pgsql-bin
  - copy /y *.exe osm2pgsql-bin
  - copy /y ..\*.style osm2pgsql-bin
  - copy /y ..\*.lua osm2pgsql-bin
  - copy /y %PREFIX%\bin\lua.dll osm2pgsql-bin
  - copy /y "%PSQL_ROOT%\bin\libpq.dll" osm2pgsql-bin
  - copy /y "%PSQL_ROOT%\bin\libintl-8.dll" osm2pgsql-bin
  - copy /y "%PSQL_ROOT%\bin\libeay32.dll" osm2pgsql-bin
  - copy /y "%PSQL_ROOT%\bin\ssleay32.dll" osm2pgsql-bin
  - 7z a c:\osm2pgsql\osm2pgsql_%Configuration%.zip osm2pgsql-bin -tzip

test_script:
  - set PATH=c:\osm2pgsql\build\osm2pgsql-bin;%PATH%
  - set PROJ_LIB=c:\libs\share
  - cd c:\osm2pgsql\build
  - ctest -VV -L NoDB
#  - ctest -VV -LE FlatNodes # enable when Postgis will be available


artifacts:
  - path: osm2pgsql_Release.zip
    name: osm2pgsql_Release.zip
